# Generated by Django 4.2.7 on 2024-01-17 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='account/images/')),
                ('blood_group', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+')], max_length=25)),
                ('age', models.CharField(max_length=2)),
                ('last_donate', models.DateTimeField()),
                ('can_donate', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
