# Generated by Django 4.2.7 on 2024-01-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='blood_group',
            field=models.CharField(choices=[('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('AB-', 'AB-'), ('A+', 'A+'), ('O-', 'O-'), ('B-', 'B-')], max_length=25),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_donate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
