# Generated by Django 4.2.7 on 2024-01-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='blood_group',
            field=models.CharField(choices=[('B-', 'B-'), ('O-', 'O-'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A-', 'A-'), ('A+', 'A+'), ('B+', 'B+')], max_length=25),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_donate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
