# Generated by Django 4.2.7 on 2024-01-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_useraccount_blood_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBloodGroup',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('AB+', 'AB+'), ('B-', 'B-'), ('B+', 'B+'), ('O-', 'O-'), ('AB-', 'AB-'), ('A-', 'A-'), ('O+', 'O+')], max_length=25),
        ),
    ]
