# Generated by Django 4.2.7 on 2024-01-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_userbloodgroup_alter_useraccount_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='blood_group',
        ),
    ]
