# Generated by Django 4.2.7 on 2024-01-18 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_useraccount_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='blood_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_group', to='account.userbloodgroup'),
        ),
    ]
