# Generated by Django 4.2.7 on 2024-01-18 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_userbloodgroup_useraccount_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForBlood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('village', models.CharField(max_length=100)),
                ('Upazila', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=200)),
                ('blood_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userbloodgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
