# Generated by Django 4.2.7 on 2024-01-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforblood',
            name='psot_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestforblood',
            name='union',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
