# Generated by Django 4.2.7 on 2024-01-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_donationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforblood',
            name='is_accecpted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
