# Generated by Django 4.2.7 on 2024-01-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_requestforblood_is_accecpted'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
