# Generated by Django 4.2.7 on 2024-01-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_donationhistory_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='donation_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
